#!/usr/bin/env bash

# Define the key location (home directory)
KEY_PATH="$HOME/school"

# Generate an RSA key pair with 4096 bits, named "school", protected by passphrase "betty"
ssh-keygen -t rsa -b 4096 -N "betty" -f "$KEY_PATH"


